version: "3"

networks:
  todo:

services:

  mysql:
    image: mysql
    deploy:
      replicas: 1
      restart_policy:
        delay: 10s
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: hcbc
    volumes:
      - ./data:/var/lib/mysql
    networks:
      todo:
        aliases:
        - mysql
    ports:
        - "3306:3306"

  hcbc-service:
      image: koumiaojuan/hcbc:0.0.1-SNAPSHOT
      deploy:
        replicas: 1
        restart_policy:
          delay: 10s
      depends_on:
      - mysql
      networks:
        todo:
          aliases:
          - hcbc-service
      ports:
      - "8083:8083"
